services:
  # Servicio de aplicación PHP
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: php-app
    ports:
      - "80:80"
    environment:
      - DB_HOST=db
      - DB_USER=${DB_USER:-appuser}
      - DB_PASSWORD=${DB_PASSWORD:-apppassword}
      - DB_NAME=${DB_NAME:-myapp}
    depends_on:
      - db
    networks:
      - app-network
    # Comentado para Windows: los archivos ya están copiados en el Dockerfile
    # Para desarrollo en Linux/Mac, descomenta esta línea:
    # volumes:
    #   - ./app:/var/www/html
    restart: unless-stopped

  # Servicio de base de datos MySQL
  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-rootpassword}
      MYSQL_DATABASE: ${DB_NAME:-myapp}
      MYSQL_USER: ${DB_USER:-appuser}
      MYSQL_PASSWORD: ${DB_PASSWORD:-apppassword}
    ports:
      - "3307:3306"
    networks:
      - app-network
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  db-data:
    driver: local

networks:
  app-network:
    driver: bridge
